# print(ord('"'))
# print(type(ord))
# print(ord(''))
# print(type(type))

print(len(''))
print(len('1947'))
print(max('1947'))
print(max('Zero'))
print(ord('Z'))
print(ord('r'))
print(ord('z'))
print(max(''))
